cleanup

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -40,26 +40,41 @@ if [[ "$OSTYPE" == "darwin"* ]]; then
 
   echo '[-] installing essential packages [-]'
   brew update
-  brew install curl wget git coreutils watch ncdu cmake ninja tree zig parallel tmux ripgrep jq
-  brew install google-chrome alacritty orbstack maccy tree-sitter tldr font-hack
+  brew install curl wget git coreutils watch ncdu cmake ninja tree parallel tmux ripgrep jq
+  brew install google-chrome alacritty orbstack maccy tree-sitter zig tldr font-hack
 else
-  echo '[-] installing essential packages [-]'
-  sudo apt-get update && sudo apt-get upgrade -y
-  sudo apt-get install -y curl wget zip zsh git coreutils gcc clang cmake make ninja-build
-  sudo apt-get install -y alacritty parallel watch tree vim tmux ripgrep jq ncdu tldr
-
-  echo '[-] downloading zig executable [-]'
-  curl -s https://ziglang.org/download/index.json \
-    | jq -r 'to_entries | map(select(.key != "master")) | max_by(.key | split(".") | map(tonumber)) | .value["x86_64-linux"].tarball' \
-    | xargs wget
-  tar -xf zig-x86_64-linux-*.tar.xz
-  sudo mv zig-x86_64-linux-*/zig /usr/bin/zig
-  if [ -d '/usr/lib/zig' ] ; then
-    sudo rm -rf /usr/lib/zig
+  echo '[-] checking secure boot state [-]'
+  if [[ "$(mokutil --sb-state)" != *"SecureBoot enabled"* ]]; then
+    echo "could not determine the secure boot state."
+    exit 1
   fi
-  sudo mkdir -p /usr/lib/zig
-  sudo mv zig-x86_64-linux*/lib/* /usr/lib/zig/
-  rm -rf zig-x86_64-linux-*
+
+  echo '[-] installing essential packages [-]'
+  sudo dnf upgrade -y
+  sudo dnf install -y curl wget zip zsh git coreutils gcc clang cmake make ninja-build ncdu
+  sudo dnf install -y alacritty zig parallel watch tree vim tmux ripgrep jq xclip redshift
+
+  if lspci | grep -E "VGA|3D" | grep -iq "AMD"; then
+    echo '[-] enabling rpm fusion repositories [-]'
+    sudo dnf install -y https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
+    sudo dnf install -y https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
+    ln -sfn $(pwd)/MangoHud $XDG_CONFIG_HOME/MangoHud
+    echo '[-] installing steam essential packages [-]'
+    sudo dnf install -y steam rocm-smi mangohud flatpak
+    echo 'remember to add `mangohud %command%` to steam launch options'
+  fi
+
+  target_dir=$XDG_DATA_HOME/elementary-xfce
+  if [ ! -d "$target_dir" ] ; then
+    echo '[-] building elementary icons for xfce [-]'
+    sudo dnf install -y gcc gdk-pixbuf2-devel gtk-update-icon-cache make optipng pkgconf rsvg-pixbuf-loader
+    git clone https://github.com/shimmerproject/elementary-xfce $target_dir
+    cd $target_dir
+    ./configure
+    make
+    sudo make install
+    sudo make icon-caches
+  fi
 
   target_dir=$XDG_DATA_HOME/fonts
   if [ ! -d "$target_dir" ] ; then
@@ -69,6 +84,15 @@ else
     unzip Hack-v3.003-ttf.zip -d $target_dir
     rm -f Hack-v3.003-ttf.zip
     fc-cache -f -v
+  fi
+
+  target_dir=$XDG_DATA_HOME/ibus-bamboo
+  if [ ! -d "$target_dir" ] ; then
+    echo '[-] building ibus-bamboo [-]'
+    sudo dnf install -y ibus make go libX11-devel libXtst-devel gtk3-devel
+    git clone https://github.com/BambooEngine/ibus-bamboo.git $target_dir
+    cd $target_dir
+    sudo make install PREFIX=/usr
   fi
 fi
 
